[manifest]
version = "1.2"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """    local badges = {}"""
position = "after"
payload = """
            if self.is_null or SMODS.has_enhancement(self, "m_akyrs_scoreless") then
                loc_vars.nominal_chips = nil
            end
"""
overwrite = true
match_indent = true

